@startuml
!includeurl C4/C4_Context.puml

Person(user, "User", "Пользователь системы Теплый дом")
System(sensors, "Датчики", "Отправляют информацию о температуре")
System(warmHouse, "Тёплый дом", "Организует удалённое управление отоплением в доме")

Rel(user, warmHouse, "Включить/Отключить отопление", "REST-запрос")
BiRel(user, warmHouse, "Получить текущую температуру", "REST-запрос")
Rel(sensors, warmHouse, "отправить информацию о температуре", "REST-запрос")

@enduml